#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Refresh vendor/zagros from a pinned Zagros panel checkout.
#
# The node is a STANDALONE project (fork of marzban-node), but the core
# drivers (xray / sing-box / openvpn / wireguard / ssh / softether / pptp)
# are owned by the panel. Vendoring a pinned snapshot keeps the node
# self-contained — no network at build/runtime, no import of panel-only
# modules — while `ZAGROS_REF` makes the provenance auditable and the
# refresh a one-command operation.
#
#   ./tools/sync-vendor.sh /path/to/Zagros [ref]
# ---------------------------------------------------------------------------
set -euo pipefail

SRC="${1:?usage: sync-vendor.sh <zagros-source-dir> [ref]}"
REF="${2:-main}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$HERE/vendor/zagros"

[ -d "$SRC/app/cores" ] || { echo "error: $SRC does not look like a Zagros checkout" >&2; exit 1; }

rm -rf "$DEST"
mkdir -p "$DEST/app"

# --- the core runtime: every driver + the CoreManager ----------------------
cp -a "$SRC/app/cores" "$DEST/app/cores"
cp -a "$SRC/app/crypto" "$DEST/app/crypto"

# --- the tiny helpers the drivers import ----------------------------------
mkdir -p "$DEST/app/studio" "$DEST/app/utils" "$DEST/app/persistence"
cp -a "$SRC/app/studio/headers.py" "$DEST/app/studio/headers.py"
cp -a "$SRC/app/studio/certs.py"   "$DEST/app/studio/certs.py"
cp -a "$SRC/app/utils/crypto.py"   "$DEST/app/utils/crypto.py"
cp -a "$SRC/app/persistence/cipher.py" "$DEST/app/persistence/cipher.py"
[ -f "$SRC/app/utils/__init__.py" ] && cp -a "$SRC/app/utils/__init__.py" "$DEST/app/utils/__init__.py"
touch "$DEST/app/utils/__init__.py"

# --- minimal package inits -------------------------------------------------
# The panel's `app/__init__.py` builds the FastAPI app and
# `app/persistence/__init__.py` imports the whole SQL layer; the node must
# never import either. These stubs keep the vendored tree import-clean and
# are regenerated on every sync.
cat > "$DEST/app/__init__.py" <<'PY'
"""Vendored Zagros core runtime — see tools/sync-vendor.sh.

This is NOT the panel's `app` package: it is a deliberately minimal
namespace that only carries driver-facing modules. Regenerated by the
sync script; edit the script, not this file.
"""
__version__ = "vendored"
PY

cat > "$DEST/app/studio/__init__.py" <<'PY'
"""Vendored subset of app.studio (only the driver-facing helpers)."""
PY

cat > "$DEST/app/persistence/__init__.py" <<'PY'
"""Vendored subset of app.persistence (only the secrets cipher)."""
PY

# --- pinned PPTP engine (accel-ppp) ---------------------------------------
# The PPTP core's daemon is built from an immutable, sha256-verified
# upstream commit archive; the node image builds the same artefact as the
# panel image so both run byte-identical engine versions.
if [ -f "$SRC/vendor/accel-ppp/manifest.json" ]; then
  mkdir -p "$HERE/vendor"
  cp -a "$SRC/vendor/accel-ppp/manifest.json" "$HERE/vendor/accel-ppp-manifest.json"
fi

# --- provenance ------------------------------------------------------------
COMMIT="unknown"
if command -v git >/dev/null 2>&1 && git -C "$SRC" rev-parse HEAD >/dev/null 2>&1; then
  COMMIT="$(git -C "$SRC" rev-parse HEAD)"
  REF="$(git -C "$SRC" describe --tags --always 2>/dev/null || echo "$REF")"
fi
{
  echo "source:  https://github.com/ZagrosGM/Zagros"
  echo "ref:     $REF"
  echo "commit:  $COMMIT"
  echo "synced:  $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "vendored paths:"
  echo "  app/cores/**        — core drivers, CoreManager, registry, types"
  echo "  app/crypto/**       — AES-GCM + X25519 primitives"
  echo "  app/studio/{headers,certs}.py"
  echo "  app/utils/crypto.py"
  echo "  app/persistence/cipher.py"
} > "$DEST/VENDORED_FROM.txt"

find "$DEST" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "$DEST" -name '*.pyc' -delete 2>/dev/null || true

echo "vendored Zagros core runtime from $REF ($COMMIT)"
find "$DEST" -name '*.py' | wc -l | xargs echo "  python files:"
